# Generated by Django 3.2.25 on 2025-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.AddField(
            model_name='facility',
            name='image',
            field=models.ImageField(default='facilities/default.jpg', upload_to='facilities/'),
        ),
        migrations.AddField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
