# Generated by Django 3.2.25 on 2024-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdm2', '0002_auto_20240824_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middaymeal',
            name='kheer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='खीर'),
        ),
        migrations.AlterField(
            model_name='middaymeal',
            name='sprouts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='स्प्राऊट्स'),
        ),
    ]
