# Generated by Django 3.2.25 on 2024-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpps_faculty', '0002_auto_20240729_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
