# Generated by Django 3.2.25 on 2024-08-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='ebook',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='ebook_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
