# Generated by Django 3.2.25 on 2025-01-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_database', '0002_auto_20240901_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
