# Generated by Django 3.2.25 on 2024-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.ActivityImage'),
        ),
    ]
