# Generated by Django 3.2.25 on 2024-07-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20240731_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='images',
            field=models.CharField(default='', max_length=500),
        ),
    ]
