# Generated by Django 3.2.25 on 2024-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20240731_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
