# Generated by Django 3.2.25 on 2024-08-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MidDayMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(verbose_name='अ.क्रं.')),
                ('day', models.CharField(max_length=50, verbose_name='वार')),
                ('food_item', models.CharField(max_length=200, verbose_name='पदार्थ')),
                ('kheer', models.CharField(blank=True, max_length=200, verbose_name='खीर')),
                ('sprouts', models.CharField(blank=True, max_length=200, verbose_name='स्प्राऊट्स')),
            ],
        ),
    ]
